encyclopedia/urls.py
from django.urls import path
from . import views

app_name= "encyclopedia"

urlpatterns = [
    path("", views.index, name="index"),
    path("wiki/<str:title>",views.get,name="get"),
    path("search",views.search,name="search"),
    path("create",views.add,name="add"),
    path("edit",views.edit,name="edit"),
    path("random",views.random,name="random")
]

wiki/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("encyclopedia.urls")),
     
]

encyclopedia/models.py
from django.db import models

# Create your models here.

encyclopedia/views.py
from django.shortcuts import render,redirect
from django.http import HttpResponse
from markdown2 import markdown
from django import forms
import re
from random import randint
from . import util

class NewForm(forms.Form):
    title = forms.CharField(label="", widget=forms.TextInput(
        attrs={'placeholder': "Enter title", 'class': 'col-sm-6 mx-auto p-2'}
    ))
    content = forms.CharField(label="", widget=forms.Textarea(
        attrs={'placeholder': "Enter Markdown content", 'class': 'col-sm-9 mx-auto p-2'}
    ))

def index(request):
    return render(request, "encyclopedia/index.html", {
        "entries": util.list_entries()
    })

def get(request, title):
    markdown_content=util.get_entry(title)
    html = ''
    if markdown_content:
       html=markdown(markdown_content)
    return render(request,'encyclopedia/entry.html', {'content': html, 'title': title})

def search(request):

    title=request.POST['q'].lower()
    entries=util.list_entries()
    for entry in entries:
        if entry.lower()==title:
          return redirect('encyclopedia:get',entry)
    # search start ...
    matched=[]
    for entry in entries:
        if re.search(title,entry.lower()):
            matched.append(entry)

    # search ends .
    message= ''
    if not matched: # No match found
          message = 'Could not find what you are looking for.'
          print(matched)
    
    return render(request,'encyclopedia/search.html', {'entries': matched, 'message': message})

def add(request):
    if request.method=="POST":
        message=""
        form = NewForm(request.POST)
        if form.is_valid():
            title = form.cleaned_data["title"].lower()
            content = form.cleaned_data["content"]
            entries=set(entry.lower() for entry in util.list_entries())
            if title not in entries:
                if title[0].islower():
                     title = title.capitalize()
                util.save_entry(title,content)
                return redirect('encyclopedia:get',title)
            else:
                message = "A page with this title already exists!, please enter a unique title."
                form = NewForm() 
        else:
            form = NewForm()
        return render(request,'encyclopedia/add.html', {"form" : form, "message" : message})
    else:
        return render(request,'encyclopedia/add.html', {"form" : NewForm(), "message" : ""})

def edit(request):
    if request.method=="POST":
         form = NewForm(request.POST)
         if form.is_valid():
          title = form.cleaned_data["title"]
          content = form.cleaned_data["content"]
          if title[0].islower():
              title = title.capitalize()
          util.save_entry(title,content)
          return redirect('encyclopedia:get',title)
    title = request.GET["edit"]
    content=util.get_entry(title)
    form = NewForm(initial={'title':title,'content':content})
    return render(request,'encyclopedia/edit.html',{"form": form})

def random(request):
    entries = util.list_entries()
    idx=randint(0,len(entries))
    title = entries[idx-1]
    return redirect('encyclopedia:get',title)
        

encyclopedia/templates/encyclopedia/add.html
{% extends 'encyclopedia/layout.html' %} 

{% load crispy_forms_tags %}

{% block  title %} 
     Create 
{% endblock %} 

{% block body %} 
    {% if message %}
       <div class="alert alert-danger" role="alert">
          {{ message }}
       </div>
    {% endif %}
    <div class="contianer">
        <div class="row">
            <div class="col-12">
                <form class="form-group" action="{% url 'encyclopedia:add' %}" method="POST">
                    {% csrf_token %}
                    <div class="text-center p-1 m-1">
                        <h3>Title</h3>
                    </div>
                    {{ form.title|as_crispy_field }}
                    <div class="text-center p-1">
                        <h3>Content</h3>
                    </div>
                    {{ form.content|as_crispy_field }}
                    <div class="form-group row">
                        <div class="form-group col-12 p-2 text-center" style="font-size:large">
                            <button type="submit" class="btn btn-primary">Create</button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
{% endblock %} 

encyclopedia/templates/encyclopedia/edit.html
{% extends 'encyclopedia/layout.html' %} 

{% load crispy_forms_tags %}

{% block  title %} 
     Edit
{% endblock %} 

{% block body %} 
    <div class="contianer">
        <div class="row">
            <div class="col-12">
                <form class="form-group" action="{% url 'encyclopedia:edit' %}" method="POST">
                    {% csrf_token %}
                    <div class="text-center p-1 m-1">
                        <h3>Title</h3>
                    </div>
                    {{ form.title|as_crispy_field }}
                    <div class="text-center p-1">
                        <h3>Content</h3>
                    </div>
                    {{ form.content|as_crispy_field }}
                    <div class="form-group row">
                        <div class="form-group col-12 p-2 text-center" style="font-size:large">
                            <button type="submit" class="btn btn-primary">Save</button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
{% endblock %} 

encyclopedia/templates/encyclopedia/entry.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    {{ title }}
{% endblock %}

{% block  body%}
     {{ content|safe }}
     {% if not content %}
        <div class="alert alert-danger text-center" role="alert"><h2>Error! requested page was not found.</h2></div>
     {% else %} 
      <form action="{% url 'encyclopedia:edit'%}" method="GET">
        <div class="text-center p-2">
            <button class="btn btn-primary" name="edit" value="{{ title }}" type="submit">Edit the content of this page</button>
         </div>
      </form>
     {% endif %}
{% endblock %}

encyclopedia/templates/encyclopedia/index.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Encyclopedia
{% endblock %}

{% block body %}
    <h1>All Pages</h1>

    <ul>
        {% for entry in entries %}
            <a href="{% url 'encyclopedia:get' entry %}"><li>{{ entry }}</li></a>
        {% endfor %}
    </ul>

{% endblock %}

encyclopedia/templates/encyclopedia/layout.html
{% load static %}

<!DOCTYPE html>

<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>{% block title %}{% endblock %}</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
        <link href="{% static 'encyclopedia/styles.css' %}" rel="stylesheet">
    </head>
    <body>
      <div class="container-fluid">
        <div class="row">
            <div class="sidebar col-md-3 col-lg-2">
                <h2>Wiki</h2>
                <form action="{% url 'encyclopedia:search' %}" method="POST">
                    {% csrf_token %} 
                    <input class="search" type="text" name="q" placeholder="Search Encyclopedia">
                </form>
                <div>
                    <a href="{% url 'encyclopedia:index' %}">Home</a>
                </div>
                <div>
                    <a href="{% url 'encyclopedia:add' %}">Create New Page</a>
                </div>
                <div>
                    <a href="{% url 'encyclopedia:random' %}">Random Page</a>
                </div>
                <!--
                {% block nav %}
                {% endblock %}-->
            </div>
            <div class="col-lg-10 col-md-9">
                {% block body %}
                {% endblock %}
            </div>
        </div>
       </div>
    </body>
</html>

encyclopedia/templates/encyclopedia/search.html
{% extends 'encyclopedia/layout.html' %}

{% block title %}
   Search
{% endblock %}

{% block body %}
   {% if message %}
      <div class="alert alert-danger text-center" role="alert"><h2>{{ message }}</h2></div>
   {% else %}
     <h1>Your search results</h1>
     <ul>
       {% for entry in entries %}
          <a href="{% url 'encyclopedia:get' entry  %}"><li>{{ entry }}</li></a>
       {% endfor %}
     </ul>
   {% endif %}
     
{% endblock %}